# pre-commit configuration file
#
# I use pre-commit.ci to run all pre-commit hooks with GitHub actions,
# such that they get automatically fixed and committed when possible.
#
# This makes sure that, when developers forget to run pre-commit hooks locally,
# the codebase still stays clean.

exclude: '^.github/workflows/'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    # This version is automatically managed.
    # The '.github/workflows/pre-commit-update.yaml' workflow runs `uv run pre-commit autoupdate` according to a schedule (cronjob).
    # If a newer version is found, that workflow updates this line and opens a Pull Request with the changes.
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    # This version is automatically managed.
    hooks:
    # Run ruff linter with auto-fix
    -   id: ruff
        args: [--fix]
    # Run ruff formatter
    -   id: ruff-format
    # Check if okay now
    -   id: ruff-check

# pre-commit.ci
ci:
    autofix_commit_msg: |
        [pre-commit.ci] Auto fixes from pre-commit hooks

    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] Pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
