# This configuration file is for pre-commit, a framework for managing and maintaining multi-language pre-commit hooks.
# The pre-commit tool is ran before committing code to ensure code quality and consistency.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    # This version is automatically managed by the '.github/workflows/pre-commit-update.yaml' workflow.
    # The pre-commit-update.yaml workflow is necessary because Dependabot does not support updating pre-commit hooks.
    # The '.github/workflows/pre-commit-update.yaml' workflow runs `uv run pre-commit autoupdate` according to a schedule (cronjob).
    # If a newer version is found, that workflow updates this line and opens a Pull Request with the changes.
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    # This version is automatically managed by the '.github/workflows/pre-commit-update.yaml' workflow.
    hooks:
    # Run ruff linter with auto-fix
    -   id: ruff
        args: [--fix]
    # Run ruff formatter
    -   id: ruff-format
