# override other configs here
name: "family_tree"
max_branching_factor: 5
max_tree_depth: 5
max_tree_size: 26
negative_facts: true
num_samples: 100
output_dir: "./data/asp/out-reldata"
quiet: false
seed: 23
stop_prob: 0
ontology_path: "./data/asp/family_tree.asp"
