# RRN Configuration File


defaults:
  - data: default
  - model: default
  - hyperparams: default
  - _self_


# # Data settings
# data:
#   # Override data settings here if needed

# # Model settings
# model:
#   # Override data settings here if needed

# # Hyperparameters settings
# hyperparams:
#   # Override data settings here if needed


use_amp: true # Enable Automatic Mixed Precision (which uses float16 where appropriate)
num_nodes: 1
verbose: true
log_dir: "./logs"
max_epochs: 1000
do_test: true
test_base_facts: true
loss_function:
  _target_: torch.nn.BCEWithLogitsLoss
metrics:
  - accuracy
  - f1_score

callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val_loss"
    patience: 50
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: "./checkpoints"
    filename: "best-checkpoint"
    monitor: "val_loss"
    save_top_k: 1
    mode: "min"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "${oc.env:WANDB_PROJECT, 'rrn-experiments'}"
  entity: "${oc.env:WANDB_ENTITY, null}"
  log_model: true
  save_dir: "${log_dir}"
  offline: false
