defaults:
  - dataset: family_tree
  - _self_

# Required: path to the dlv executable
dlv: /usr/local/bin/dlv/dl

# Train/test split
train_val_pct: 0.8
# this means test size is (1 - train_val_pct)

# Validation pct
val_pct: 0.1
# this means val size is val_pct * (train + val)

# -> 80% train, 10% val, 10% test
