defaults:
  - _self_

ontology:
  path: "data/ont/input/family.ttl"

graph_output_path: "data/ont/output/family-single/graphs/"
proof_output_path: "data/ont/output/family-single/proofs/"

dataset:
  output_dir: "data/ont/output/family-single"
  seed: 23

export_proofs: true
export_graphs: true
visualize_negatives: false

generator:
  max_recursion: 2
  global_max_depth: 5
  max_proofs_per_atom: 2
  individual_pool_size: 50
  individual_reuse_prob: 0.9
  use_signature_sampling: true
  min_proof_roots: 1
  max_proof_roots: 10
  always_generate_base_facts: false

negative_sampling:
  strategy: "proof_based"
  ratio: 1.0
  corrupt_base_facts: true

logging:
  level: DEBUG
